version: '3.8'
x-aws-vpc: "vpc-e26e5687"
services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - ./database-data:/data/db
volumes:
  mongodb_data_container: