version: '3.3'
services:
  course_user:  
    container_name: course_user
    image: index.docker.io/maklisa2000/rmit_e_learning_user_backend
    networks:
      - local_net
    depends_on:
      - db
    ports:
      - "8081:8081"

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    container_name: mongodb
    networks:
      - local_net
    volumes:
      - ./database-data:/data/db

volumes:
  mongodb_data_container:

networks:
  local_net:
    driver: bridge