name: ON_PUSH_COURSE_BACKEND

on:
  push:
    branches: [ course-backend ]
  pull_request:
    branches: [ course-backend ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup jdk-17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package -DskipTests=true --file pom.xml

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: maklisa2000/rmit_e_learning
          tags: course_backend:latest

